name: popi_biking_fresh
description: "Popi Is Biking - Fresh start with working GPS"
publish_to: 'none'

version: 1.3.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  flutter_riverpod: ^3.0.1

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  mapbox_maps_flutter: ^2.6.0

  # Location
  geolocator: ^14.0.2
  flutter_compass: ^0.8.0

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_crashlytics: ^5.0.2

  # HTTP & API
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Load .env file for API keys (only in development)
  # For production, use build-time environment variables
  # - .env
