name: popi_biking_fresh
description: "Popi Is Biking - Fresh start with working GPS"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  mapbox_maps_flutter: ^2.6.0

  # Location
  geolocator: ^12.0.0
  permission_handler: ^11.4.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # HTTP & API
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Load .env file for API keys
  assets:
    - .env
