// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1atb61TBjZV-IVdTagh7J2nGKMUn4QM4',
    appId: '1:762853433576:web:5cb93bb60f2915e2e4a95d',
    messagingSenderId: '762853433576',
    projectId: 'popi-biking-zen-mode',
    authDomain: 'popi-biking-zen-mode.firebaseapp.com',
    storageBucket: 'popi-biking-zen-mode.firebasestorage.app',
    measurementId: 'G-7Q9GQ55CKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1atb61TBjZV-IVdTagh7J2nGKMUn4QM4',
    appId: '1:762853433576:web:5cb93bb60f2915e2e4a95d',
    messagingSenderId: '762853433576',
    projectId: 'popi-biking-zen-mode',
    storageBucket: 'popi-biking-zen-mode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHD5kxe_c8xUzFmOXkF7rGMs0hyfV96yU',
    appId: '1:762853433576:ios:41c7afc59ff30815e4a95d',
    messagingSenderId: '762853433576',
    projectId: 'popi-biking-zen-mode',
    storageBucket: 'popi-biking-zen-mode.firebasestorage.app',
    iosBundleId: 'com.wike.wikeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1atb61TBjZV-IVdTagh7J2nGKMUn4QM4',
    appId: '1:762853433576:web:5cb93bb60f2915e2e4a95d',
    messagingSenderId: '762853433576',
    projectId: 'popi-biking-zen-mode',
    storageBucket: 'popi-biking-zen-mode.firebasestorage.app',
    iosBundleId: 'com.wike.wikeFlutter',
  );
}

